import {
  GraduationCap, Microscope, Heart, Building2, ArrowRight, BookOpen, Users, Award, Globe,
  Stethoscope, FlaskConical, Hospital, Shield, Target, Lightbulb, Brain, HeartPulse, Activity,
  BarChart, TrendingUp, Briefcase, Medal, Star, CheckCircle, Plus, Minus, X, Menu,
  ChevronRight, ChevronLeft, ChevronUp, ChevronDown, Search, Mail, Phone, MapPin, ExternalLink,
  Download, Upload, File, FileText, Image, Video, Calendar, Clock, Bell, Settings, User,
  LogIn, LogOut, Eye, EyeOff, Lock, Unlock, RefreshCw, Home, Sun, Moon, HelpCircle,
  University, Newspaper, Link, Compass, Wifi, UtensilsCrossed, Store, Coffee, ClipboardCheck,
  Leaf, HeartHandshake, Dumbbell, Trophy, Waves, Sparkles, Vote, Syringe, Palette, MicVocal,
  HandHeart, Music, Equal, Accessibility, Church, Plane, Camera, IdCard, Bus, Ambulance,
  Printer, Library, Quote, Megaphone, Gavel, Scale, School, UserPlus, Crown, Landmark,
  DollarSign, BarChart3, BadgeCheck, CheckCircle2, Pill, AlertCircle, XCircle, AlertTriangle,
  Loader, Loader2, CreditCard, Wallet, ArrowLeft, ArrowUp, RotateCcw, MessageCircle, Send,
  CheckCheck, Play, Pause, Filter,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  GraduationCap,
  Microscope,
  Heart,
  Building2,
  ArrowRight,
  BookOpen,
  Users,
  Award,
  Globe,
  Stethoscope,
  FlaskConical,
  Hospital,
  Shield,
  Target,
  Lightbulb,
  Brain,
  HeartPulse,
  Activity,
  BarChart,
  TrendingUp,
  Briefcase,
  Medal,
  Star,
  CheckCircle,
  Plus,
  Minus,
  X,
  Menu,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Search,
  Mail,
  Phone,
  MapPin,
  ExternalLink,
  Download,
  Upload,
  File,
  FileText,
  Image,
  Video,
  Calendar,
  Clock,
  Bell,
  Settings,
  User,
  LogIn,
  LogOut,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  RefreshCw,
  Home,
  Sun,
  Moon,
  University,
  Newspaper,
  Link,
  Compass,
  Wifi,
  UtensilsCrossed,
  Store,
  Coffee,
  ClipboardCheck,
  Leaf,
  HeartHandshake,
  Dumbbell,
  Trophy,
  Waves,
  Sparkles,
  Vote,
  Syringe,
  Palette,
  Microphone: MicVocal,
  MicVocal,
  HandHeart,
  Music,
  Equal,
  Accessibility,
  Church,
  Plane,
  Camera,
  IdCard,
  Bus,
  Ambulance,
  Printer,
  Library,
  Quote,
  Megaphone,
  Gavel,
  Scale,
  School,
  UserPlus,
  Crown,
  Landmark,
  DollarSign,
  BarChart3,
  BadgeCheck,
  CheckCircle2,
  Pill,
  AlertCircle,
  XCircle,
  AlertTriangle,
  Loader,
  Loader2,
  CreditCard,
  Wallet,
  ArrowLeft,
  ArrowUp,
  RotateCcw,
  MessageCircle,
  Send,
  CheckCheck,
  Play,
  Pause,
  Filter,
};

export function getLucideIcon(name: string): LucideIcon {
  return iconMap[name] ?? HelpCircle;
}
