# Generated by Django 5.2.12 on 2026-06-06 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_college_faculty_members_count_college_icon_name_and_more'),
        ('portals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(blank=True, help_text='Course code e.g., CPD-2024-001', max_length=30)),
                ('category', models.CharField(choices=[('clinical', 'Clinical Medicine'), ('surgery', 'Surgery'), ('public_health', 'Public Health'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('lab_science', 'Lab Science'), ('health_admin', 'Health Administration'), ('research', 'Research Methodology'), ('general', 'General Medical Education')], default='general', max_length=20)),
                ('description', models.TextField()),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objectives')),
                ('curriculum', models.JSONField(blank=True, default=list, help_text='List of modules/topics')),
                ('duration_hours', models.PositiveIntegerField(default=8)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('credit_hours', models.PositiveIntegerField(default=0, help_text='CPD credit hours awarded')),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment_deadline', models.DateField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=50)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('fee_local', models.DecimalField(blank=True, decimal_places=2, help_text='Fee in NGN', max_digits=10, null=True)),
                ('fee_intl', models.DecimalField(blank=True, decimal_places=2, help_text='Fee in USD', max_digits=10, null=True)),
                ('instructor_name', models.CharField(blank=True, help_text='Display name if instructor not in system', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cpd/thumbnails/')),
                ('syllabus_file', models.FileField(blank=True, null=True, upload_to='cpd/syllabus/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpd_courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPD Course',
                'verbose_name_plural': 'CPD Courses',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPDEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('completed_modules', models.JSONField(blank=True, default=list, help_text='List of completed module IDs')),
                ('quiz_scores', models.JSONField(blank=True, default=dict, help_text='Dict of quiz_id: score')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='enrolled', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portals.cpdcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPD Enrollment',
                'verbose_name_plural': 'CPD Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('assignment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='e.g., A, B+, C', max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__code'],
                'unique_together': {('student', 'course', 'session', 'semester')},
            },
        ),
    ]
