# Generated by Django 5.2.12 on 2026-06-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_studentcourse_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='e.g., A, B+, C', max_length=5)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('remark', models.CharField(blank=True, help_text='e.g., Excellent, Good, Pass', max_length=100)),
                ('level', models.PositiveIntegerField(default=100, help_text='Applies to this level (all levels if 0)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grading Scale',
                'verbose_name_plural': 'Grading Scales',
                'ordering': ['-sort_order', '-grade_point'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'ordering': ['course__code'], 'verbose_name': 'Student Course', 'verbose_name_plural': 'Student Courses'},
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='dean_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='dean_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_approved_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='result_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hod_approved', 'HOD Approved'), ('dean_approved', 'Dean Approved'), ('senate_approved', 'Senate Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='senate_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='senate_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senate_approved_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
