# Generated by Django 5.2.12 on 2026-06-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_add_course_schedule_instructor'),
        ('portals', '0005_add_progression_and_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fee'), ('acceptance', 'Acceptance Fee'), ('hostel', 'Hostel Fee'), ('lab', 'Laboratory Fee'), ('library', 'Library Fee'), ('sports', 'Sports Fee'), ('ict', 'ICT Fee'), ('development', 'Development Levy'), ('other', 'Other')], max_length=20)),
                ('code', models.CharField(help_text='Short code e.g. TUITION-100', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentfeepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Fee Payment', 'verbose_name_plural': 'Student Fee Payments'},
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='fee_type_label',
            field=models.CharField(blank=True, help_text='Snapshot of fee type name', max_length=50),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Raw gateway response', null=True),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='fee_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Fee type category (legacy field)', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('remita', 'Remita'), ('bank_deposit', 'Bank Deposit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FeeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=50)),
                ('level', models.PositiveIntegerField(help_text='Level e.g. 100, 200')),
                ('semester', models.CharField(blank=True, help_text='Blank = both semesters', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='academics.program')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portals.feetype')),
            ],
            options={
                'verbose_name': 'Fee Allocation',
                'verbose_name_plural': 'Fee Allocations',
                'ordering': ['session', 'level', 'fee_type__category'],
            },
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portals.feeallocation'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='fee_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portals.feetype'),
        ),
    ]
