# Generated by Django 5.2.12 on 2026-06-14 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_add_course_schedule_instructor'),
        ('portals', '0006_feetype_alter_studentfeepayment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='fee_type_label',
        ),
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='fee_type_ref',
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount received (may differ for scholarships)', max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='installment',
            field=models.CharField(choices=[('full', 'Full Payment'), ('first', 'First Installment'), ('second', 'Second Installment')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='is_scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='scholarship_body',
            field=models.CharField(blank=True, help_text='Scholarship body name', max_length=200),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='scholarship_ref',
            field=models.CharField(blank=True, help_text='Scholarship reference', max_length=100),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=50)),
                ('level', models.PositiveIntegerField(help_text='Level e.g. 100, 200')),
                ('semester', models.CharField(blank=True, help_text='Blank = both semesters', max_length=20)),
                ('is_indigene', models.BooleanField(default=False, help_text='True = Bayelsa indigene rate')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_installments', models.PositiveSmallIntegerField(default=2, help_text='Max installments allowed (1 or 2)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.program')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['session', 'level', 'program__title'],
                'unique_together': {('session', 'level', 'program', 'semester', 'is_indigene')},
            },
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portals.feestructure'),
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portals.feestructure')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_items', to='portals.feetype')),
            ],
            options={
                'verbose_name': 'Fee Structure Item',
                'verbose_name_plural': 'Fee Structure Items',
                'ordering': ['sort_order'],
                'unique_together': {('fee_structure', 'fee_type')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=50)),
                ('scholarship_body', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scholarship Record',
                'verbose_name_plural': 'Scholarship Records',
                'ordering': ['-session', 'student_id'],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='FeeAllocation',
        ),
    ]
