# Generated by Django 5.2.12 on 2026-08-18 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_remove_studentfeepayment_allocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g., 2025/2026', max_length=50)),
                ('hostel_name', models.CharField(max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('bed_space', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hostel Allocation',
                'verbose_name_plural': 'Hostel Allocations',
                'ordering': ['-requested_at'],
            },
        ),
    ]
