# Generated by Django 6.0.4 on 2026-04-29 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='Prof.', max_length=50)),
                ('position', models.CharField(choices=[('vc', 'Vice Chancellor'), ('deputy_vc', 'Deputy Vice Chancellor'), ('registrar', 'Registrar'), ('bursar', 'Bursar'), ('librarian', 'University Librarian'), ('dean', 'Dean'), ('head_of_dept', 'Head of Department'), ('other', 'Other')], max_length=20)),
                ('specific_role', models.CharField(blank=True, help_text="e.g., 'Dean, College of Medicine'", max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='archive/leaders/')),
                ('biography', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('current_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Past Leader',
                'verbose_name_plural': 'Past Leaders',
                'ordering': ['-start_year', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UniversityTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='archive/timeline/')),
                ('category', models.CharField(blank=True, help_text="e.g., 'founding', 'milestone', 'expansion'", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University Timeline Event',
                'verbose_name_plural': 'University Timeline',
                'ordering': ['year', 'month', 'day', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('research', 'Research'), ('community', 'Community'), ('academic', 'Academic'), ('announcement', 'Announcement'), ('event', 'Event'), ('achievement', 'Achievement')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='archive/news/')),
                ('author', models.CharField(max_length=200)),
                ('original_published_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_id', models.PositiveIntegerField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived News',
                'verbose_name_plural': 'Archived News Items',
                'ordering': ['-original_published_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('charter', 'University Charter'), ('statute', 'Statute'), ('regulation', 'Regulation'), ('circular', 'Circular'), ('report', 'Annual Report'), ('minutes', 'Minutes'), ('correspondence', 'Correspondence'), ('photograph', 'Historical Photograph'), ('other', 'Other')], max_length=20)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('document_year', models.PositiveIntegerField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='archive/documents/')),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historical Document',
                'verbose_name_plural': 'Historical Documents',
                'ordering': ['-document_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('ceremony', 'Ceremony'), ('symposium', 'Symposium'), ('workshop', 'Workshop'), ('outreach', 'Outreach'), ('social', 'Social'), ('seminar', 'Seminar'), ('webinar', 'Webinar')], max_length=20)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('research', 'Research'), ('community', 'Community'), ('professional', 'Professional'), ('alumni', 'Alumni'), ('student', 'Student')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='archive/events/')),
                ('gallery_images', models.TextField(blank=True, help_text='Comma-separated image paths')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Event summary/recap')),
                ('key_highlights', models.TextField(blank=True, help_text='Key highlights from the event')),
                ('attendees_count', models.PositiveIntegerField(blank=True, null=True)),
                ('proceedings_document', models.FileField(blank=True, null=True, upload_to='archive/proceedings/')),
                ('presentations_zip', models.FileField(blank=True, null=True, upload_to='archive/presentations/')),
                ('speakers', models.TextField(blank=True, help_text='List of speakers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Past Event',
                'verbose_name_plural': 'Past Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
