# Generated by Django 5.2.12 on 2026-06-13 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_alumnidonation_id_alter_alumnievent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('deceased', 'Deceased'), ('deferred', 'Deferred'), ('graduated', 'Graduated'), ('alumni', 'Alumni')], help_text='Student lifecycle status', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_type', models.CharField(blank=True, choices=[('utme', 'UTME'), ('de', 'Direct Entry'), ('transfer', 'Transfer'), ('part_time', 'Part-time'), ('sandwich', 'Sandwich')], max_length=20, null=True)),
                ('entry_mode', models.CharField(choices=[('regular', 'Regular'), ('part_time', 'Part-time'), ('sandwich', 'Sandwich')], default='regular', max_length=20)),
                ('current_level', models.PositiveIntegerField(default=100)),
                ('current_semester', models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=20)),
                ('nok_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nok_relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=50, null=True)),
                ('nok_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nok_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nok_address', models.TextField(blank=True, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('lga_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('fingerprint_hash', models.CharField(blank=True, max_length=500, null=True)),
                ('face_embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
