# Generated by Django 5.2.12 on 2026-06-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_student_status_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('admin', 'Administrator'), ('applicant', 'Applicant'), ('bursary', 'Bursary'), ('hod', 'HOD'), ('dean', 'Dean'), ('registrar', 'Registrar'), ('vc', 'Vice Chancellor')], default='applicant', max_length=20),
        ),
    ]
