# Generated by Django 6.0.4 on 2026-04-29 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges_as_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='college',
            name='provost',
            field=models.ForeignKey(blank=True, help_text='College Provost - links to user profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges_as_provost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='academics.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text='Head of Department - links to user profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='staff_members',
            field=models.ManyToManyField(blank=True, help_text='Staff members in this department', related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='academics.college'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='academics.department'),
        ),
        migrations.AddField(
            model_name='facultypublication',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='facultyunit',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='academics.college'),
        ),
        migrations.AddField(
            model_name='facultyunit',
            name='dean',
            field=models.ForeignKey(blank=True, help_text='Faculty Dean - links to user profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_as_dean', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.facultyunit'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership', to='academics.college'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership', to='academics.department'),
        ),
        migrations.AddField(
            model_name='nonacademicstaff',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_academic_staff', to='academics.college'),
        ),
        migrations.AddField(
            model_name='nonacademicstaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_academic_staff', to='academics.department'),
        ),
        migrations.AddField(
            model_name='nonacademicstaff',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='academics.nonacademicstaff'),
        ),
        migrations.AddField(
            model_name='program',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.college'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programadmissionrequirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirements', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programcurriculumyear',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_years', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programcurriculumcourse',
            name='curriculum_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.programcurriculumyear'),
        ),
        migrations.AddField(
            model_name='programfacility',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programhighlight',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='academics.program'),
        ),
        migrations.AlterUniqueTogether(
            name='sdgmetric',
            unique_together={('sdg_code', 'label')},
        ),
    ]
