# Generated by Django 6.0.4 on 2026-04-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='facultyunit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Faculty Unit', 'verbose_name_plural': 'Faculty Units'},
        ),
        migrations.AddField(
            model_name='department',
            name='college_direct',
            field=models.ForeignKey(blank=True, help_text='Direct college link for departments not under a faculty', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_direct', to='academics.college'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Link to faculty (optional if linked to college directly)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.facultyunit'),
        ),
        migrations.AlterField(
            model_name='facultyunit',
            name='college',
            field=models.ForeignKey(blank=True, help_text='Optional: leave blank for standalone faculties like Faculty of Science', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='academics.college'),
        ),
    ]
