# Generated by Django 6.0.4 on 2026-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_department_options_alter_facultyunit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonacademicstaff',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
