# Generated by Django 6.0.4 on 2026-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_nonacademicstaff_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='faculty_members_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of teaching faculty/staff in this college'),
        ),
        migrations.AddField(
            model_name='college',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name for frontend display (e.g., GraduationCap, Microscope)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='college_previews/'),
        ),
    ]
