# Generated by Django 5.2.12 on 2026-06-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_college_faculty_members_count_college_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonacademicstaff',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LeadershipPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('journal', models.CharField(max_length=300)),
                ('citations', models.PositiveIntegerField(default=0)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.leadership')),
            ],
            options={
                'verbose_name': 'Leadership Publication',
                'verbose_name_plural': 'Leadership Publications',
                'ordering': ['-year', '-citations'],
            },
        ),
        migrations.CreateModel(
            name='StaffPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('journal', models.CharField(max_length=300)),
                ('citations', models.PositiveIntegerField(default=0)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.nonacademicstaff')),
            ],
            options={
                'verbose_name': 'Staff Publication',
                'verbose_name_plural': 'Staff Publications',
                'ordering': ['-year', '-citations'],
            },
        ),
    ]
