# Generated by Django 5.2.12 on 2026-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_leadership_research_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.CharField(help_text="Text description of the deadline, e.g. 'September 30, 2025'", max_length=200)),
                ('icon_name', models.CharField(choices=[('BookOpen', 'Book Open'), ('Clock', 'Clock'), ('Calendar', 'Calendar'), ('GraduationCap', 'Graduation Cap'), ('Bell', 'Bell'), ('FileText', 'File Text'), ('AlertCircle', 'Alert Circle')], default='Calendar', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
                'ordering': ['display_order'],
            },
        ),
    ]
