# Generated by Django 5.2.12 on 2026-06-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcurriculumcourse',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional link to the actual Course record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_courses', to='academics.course'),
        ),
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10)),
                ('level', models.PositiveIntegerField(blank=True, help_text='e.g., 100, 200. Leave blank for all levels', null=True)),
                ('opens_at', models.DateTimeField(help_text='When registration opens')),
                ('closes_at', models.DateTimeField(help_text='When registration closes')),
                ('late_registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('late_registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('late_registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, help_text='Leave blank for all programs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_periods', to='academics.program')),
            ],
            options={
                'verbose_name': 'Registration Period',
                'verbose_name_plural': 'Registration Periods',
                'ordering': ['-academic_year', 'semester', 'level'],
                'unique_together': {('academic_year', 'semester', 'program', 'level')},
            },
        ),
    ]
