# Generated by Django 5.2.12 on 2026-06-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_programcurriculumcourse_course_registrationperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Max students (0 = unlimited)'),
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('is_lab', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, help_text='e.g., Group A, Tutorial Group 1', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.course')),
            ],
            options={
                'verbose_name': 'Course Schedule',
                'verbose_name_plural': 'Course Schedules',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
