# Generated by Django 5.2.12 on 2026-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_course_capacity_courseschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_count',
            field=models.PositiveIntegerField(default=0, help_text='Current enrolled students (auto-updated)'),
        ),
    ]
