# Generated by Django 5.2.12 on 2026-06-14 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_course_enrolled_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Faculty assigned to teach this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
