# Generated by Django 5.2.12 on 2026-06-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_add_course_schedule_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.college'),
        ),
    ]
