# Generated by Django 5.2.12 on 2026-06-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_program_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='provost_photo',
            field=models.ImageField(blank=True, help_text='Provost/Director profile photo', null=True, upload_to='college_leadership/'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_photo',
            field=models.ImageField(blank=True, help_text='Head of Department profile photo', null=True, upload_to='department_leadership/'),
        ),
        migrations.AddField(
            model_name='facultyunit',
            name='dean_photo',
            field=models.ImageField(blank=True, help_text='Dean profile photo', null=True, upload_to='faculty_leadership/'),
        ),
    ]
