# Generated by Django 5.2.12 on 2026-06-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_add_leader_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='academics.college'),
        ),
    ]
