# Generated by Django 5.2.12 on 2026-07-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_make_faculty_college_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCustomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display text for the link (e.g. 'Lab Website', 'Portfolio')", max_length=100)),
                ('url', models.URLField(help_text='Full URL for the link')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_links', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'Faculty Custom Link',
                'verbose_name_plural': 'Faculty Custom Links',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
