# Generated by Django 5.2.12 on 2026-08-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_facultycustomlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='position',
            field=models.CharField(choices=[('pro_chancellor', 'Pro-Chancellor'), ('vc', 'Vice Chancellor'), ('dvc_academic', 'Deputy Vice Chancellor - Academic'), ('dvc_admin', 'Deputy Vice Chancellor - Administration'), ('registrar', 'Registrar'), ('bursar', 'Bursar'), ('librarian', 'University Librarian'), ('dean', 'Dean'), ('director', 'Director'), ('hod', 'Head of Department'), ('other', 'Other')], max_length=30),
        ),
    ]
