# Generated by Django 6.0.4 on 2026-10-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_leadership_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgmetric',
            name='sdg_code',
            field=models.CharField(choices=[('sdg3', 'SDG 3: Good Health & Well-being'), ('sdg4', 'SDG 4: Quality Education'), ('sdg5', 'SDG 5: Gender Equality'), ('sdg17', 'SDG 17: Partnerships for the Goals')], max_length=10),
        ),
    ]
