# Generated by Django 6.0.4 on 2026-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_seed_sdg17_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='applications_open',
            field=models.BooleanField(default=True, help_text='Allow applicants to apply to this program'),
        ),
    ]
