# Generated by Django 6.0.4 on 2026-10-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_program_applications_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('masters', 'Masters'), ('phd', 'PhD'), ('certificate', 'Certificate'), ('professional', 'Professional')], max_length=20, unique=True)),
                ('local_fee', models.DecimalField(decimal_places=2, default=0, help_text='Application fee in NGN', max_digits=10)),
                ('intl_fee', models.DecimalField(decimal_places=2, default=0, help_text='Application fee in USD', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Fee',
                'verbose_name_plural': 'Application Fees',
                'ordering': ['level'],
            },
        ),
    ]
