# Generated by Django 6.0.4 on 2026-04-29 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('ceremony', 'Ceremony'), ('symposium', 'Symposium'), ('workshop', 'Workshop'), ('outreach', 'Outreach'), ('social', 'Social'), ('seminar', 'Seminar'), ('webinar', 'Webinar')], max_length=20)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('research', 'Research'), ('community', 'Community'), ('professional', 'Professional'), ('alumni', 'Alumni'), ('student', 'Student')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('registration_open', models.BooleanField(default=False)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('speakers', models.TextField(blank=True, help_text='One speaker per line')),
                ('agenda', models.TextField(blank=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('academics', 'Academics'), ('campus', 'Campus Life'), ('financial', 'Financial Aid'), ('international', 'International Students'), ('general', 'General')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/public/')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('financial', 'Financial'), ('research', 'Research'), ('student', 'Student'), ('staff', 'Staff'), ('strategic', 'Strategic'), ('governance', 'Governance'), ('admissions', 'Admissions'), ('general', 'General')], default='general', max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('xls', 'Excel Spreadsheet'), ('xlsx', 'Excel Spreadsheet (XLSX)'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint (PPTX)')], default='pdf', max_length=10)),
                ('file_size', models.CharField(blank=True, help_text="e.g., '8.5 MB'", max_length=20)),
                ('version', models.CharField(blank=True, help_text="e.g., '2024-2025'", max_length=50)),
                ('date_label', models.CharField(blank=True, help_text="e.g., 'January 2024' or 'Updated 2024'", max_length=50)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Document',
                'verbose_name_plural': 'Public Documents',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text="e.g., 'Student, MBBS 2024'", max_length=100)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('admissions', 'Admissions Inquiry'), ('general', 'General Inquiry'), ('partnership', 'Partnership Opportunity'), ('research', 'Research Collaboration'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for listings')),
                ('content', models.TextField(help_text='Full article content')),
                ('category', models.CharField(choices=[('research', 'Research'), ('community', 'Community'), ('academic', 'Academic'), ('announcement', 'Announcement'), ('event', 'Event'), ('achievement', 'Achievement')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('author', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Page'), ('mission_vision', 'Mission & Vision'), ('history', 'History'), ('campus_life', 'Campus Life'), ('governance', 'Governance'), ('core_values', 'Core Values'), ('strategic_pillars', 'Strategic Pillars'), ('contact_info', 'Contact Information'), ('academics_overview', 'Academics Overview')], max_length=30)),
                ('section_key', models.CharField(help_text='Unique identifier for this content block', max_length=100)),
                ('content_type', models.CharField(choices=[('text', 'Text Block'), ('hero', 'Hero Section'), ('stats', 'Statistics'), ('list', 'List Items'), ('timeline', 'Timeline'), ('gallery', 'Image Gallery'), ('feature', 'Feature Cards')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_content/')),
                ('extra_data', models.JSONField(blank=True, help_text='JSON data for structured content (stats, lists, etc.)', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['page', 'display_order', 'section_key'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
