# Generated by Django 6.0.4 on 2026-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/')),
                ('category', models.CharField(blank=True, choices=[('campus', 'Campus Life'), ('events', 'Events'), ('academic', 'Academic'), ('research', 'Research'), ('students', 'Students'), ('facilities', 'Facilities'), ('ceremonies', 'Ceremonies'), ('sports', 'Sports')], max_length=20)),
                ('event_date', models.DateField(blank=True, help_text='Date the photo was taken', null=True)),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
    ]
