# Generated by Django 6.0.4 on 2026-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_heroslide_internationalpartner_sdg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('ranking', 'Ranking'), ('accreditation', 'Accreditation'), ('achievement', 'Achievement')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('rank', models.CharField(blank=True, help_text="e.g. 'Top 5', '#1', '4.5/5'", max_length=100)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, help_text='Issuing body or source name', max_length=200)),
                ('accrediting_body', models.CharField(blank=True, max_length=100)),
                ('body_full_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, help_text="e.g. 'Full Accreditation'", max_length=100)),
                ('validity', models.CharField(blank=True, help_text="e.g. '2019 - Present'", max_length=100)),
                ('accredited_programs', models.TextField(blank=True, help_text='Comma-separated program names')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University Ranking',
                'verbose_name_plural': 'University Rankings',
                'ordering': ['entry_type', 'display_order', '-year'],
            },
        ),
    ]
