# Generated by Django 6.0.4 on 2026-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_universityranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(help_text="e.g. '1,247+', '94%'", max_length=100)),
                ('category', models.CharField(choices=[('research', 'Research & Publications'), ('academic', 'Academic'), ('impact', 'Impact'), ('partnership', 'Partnerships'), ('quality', 'Quality Assurance'), ('other', 'Other')], default='other', max_length=30)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Key Metric',
                'verbose_name_plural': 'Key Metrics',
                'ordering': ['category', 'display_order'],
            },
        ),
    ]
