# Generated by Django 5.2.12 on 2026-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_event_currency_event_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Campus Contact Info',
                'verbose_name_plural': 'Campus Contact Info',
            },
        ),
        migrations.CreateModel(
            name='CampusFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('housing', 'Residential Life'), ('dining', 'Dining & Nutrition'), ('wellness', 'Health & Wellness'), ('organizations', 'Student Organizations'), ('diversity', 'Diversity & Inclusion'), ('safety', 'Safety & Security'), ('virtual_tour', 'Virtual Tour')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name (e.g. Building2, UtensilsCrossed)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_features/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus Feature',
                'verbose_name_plural': 'Campus Features',
                'ordering': ['section_key', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CampusStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus Statistic',
                'verbose_name_plural': 'Campus Statistics',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CampusTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(blank=True, help_text="e.g. 'MBBS, Final Year'", max_length=200)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_testimonials/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus Testimonial',
                'verbose_name_plural': 'Campus Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
