# Generated by Django 5.2.12 on 2026-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_fundingorganization_fundedproject_pagecontentsimple'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityranking',
            name='logo',
            field=models.ImageField(blank=True, help_text='Accreditation body logo', upload_to='accreditations/'),
        ),
    ]
