# Generated by Django 5.2.12 on 2026-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_universityranking_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundedproject',
            name='impact',
            field=models.TextField(blank=True, help_text='Key impact or outcomes'),
        ),
        migrations.AddField(
            model_name='fundedproject',
            name='principal_investigator',
            field=models.CharField(blank=True, help_text='Lead researcher name', max_length=255),
        ),
    ]
