# Generated by Django 5.2.12 on 2026-06-17 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_fundedproject_impact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Bayelsa Medical University', max_length=200)),
                ('hero_content', models.TextField(blank=True)),
                ('about_main_title', models.CharField(blank=True, default='Our Mission & Vision', max_length=200)),
                ('about_main_content', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g., Award, Heart, Globe)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='content.aboutpage')),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g., 2018, 3,500+', max_length=50)),
                ('label', models.CharField(help_text='e.g., Founded, Students', max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='e.g., +', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.aboutpage')),
            ],
            options={
                'verbose_name': 'About Statistic',
                'verbose_name_plural': 'About Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GovernancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_content', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Governance Page',
                'verbose_name_plural': 'Governance Page',
            },
        ),
        migrations.CreateModel(
            name='GovernanceCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('focus', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='content.governancepage')),
            ],
            options={
                'verbose_name': 'Governance Committee',
                'verbose_name_plural': 'Governance Committees',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g., Supreme Governing Body', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='Array of responsibility strings')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g., Building2, Users)', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color (e.g., #1E1E1E)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governing_bodies', to='content.governancepage')),
            ],
            options={
                'verbose_name': 'Governing Body',
                'verbose_name_plural': 'Governing Bodies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='content.governancepage')),
            ],
            options={
                'verbose_name': 'Governance Policy',
                'verbose_name_plural': 'Governance Policies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_content', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Page',
                'verbose_name_plural': 'History Page',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2018', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g., Building2, Award)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='content.historypage')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_content', models.TextField(blank=True)),
                ('mission_content', models.TextField(blank=True)),
                ('vision_content', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vision & Mission Page',
                'verbose_name_plural': 'Vision & Mission Page',
            },
        ),
        migrations.CreateModel(
            name='VisionMissionPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g., Lightbulb, Heart)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_pillars', to='content.visionmissionpage')),
            ],
            options={
                'verbose_name': 'Strategic Pillar',
                'verbose_name_plural': 'Strategic Pillars',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='content.visionmissionpage')),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
    ]
