# Generated by Django 5.2.12 on 2026-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_aboutpage_aboutcorevalue_aboutstat_governancepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypage',
            name='future_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historypage',
            name='future_quote',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historypage',
            name='future_title',
            field=models.CharField(blank=True, default='Looking Ahead', max_length=200),
        ),
        migrations.AddField(
            model_name='historypage',
            name='intro_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historypage',
            name='intro_image_caption',
            field=models.CharField(blank=True, default='Campus Development Gallery', max_length=200),
        ),
        migrations.AddField(
            model_name='historypage',
            name='intro_title',
            field=models.CharField(blank=True, default='A Vision for Healthcare Excellence', max_length=200),
        ),
        migrations.AddField(
            model_name='historypage',
            name='stat_1_label',
            field=models.CharField(blank=True, default='Years of Excellence', max_length=100),
        ),
        migrations.AddField(
            model_name='historypage',
            name='stat_1_value',
            field=models.CharField(blank=True, default='7+', max_length=50),
        ),
        migrations.AddField(
            model_name='historypage',
            name='stat_2_label',
            field=models.CharField(blank=True, default='Students Trained', max_length=100),
        ),
        migrations.AddField(
            model_name='historypage',
            name='stat_2_value',
            field=models.CharField(blank=True, default='3,500+', max_length=50),
        ),
        migrations.AddField(
            model_name='historypage',
            name='stat_3_label',
            field=models.CharField(blank=True, default='Degree Programs', max_length=100),
        ),
        migrations.AddField(
            model_name='historypage',
            name='stat_3_value',
            field=models.CharField(blank=True, default='50+', max_length=50),
        ),
    ]
