# Generated by Django 5.2.12 on 2026-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_historypage_future_content_historypage_future_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypage',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_content/'),
        ),
    ]
