# Generated by Django 5.2.12 on 2026-06-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_historypage_intro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryIntroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_content/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_images', to='content.historypage')),
            ],
            options={
                'verbose_name': 'Intro Gallery Image',
                'verbose_name_plural': 'Intro Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
