# Generated by Django 5.2.12 on 2026-07-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_campusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('url', 'External URL (YouTube/Vimeo)'), ('upload', 'Uploaded Video File')], default='url', max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=...)')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file directly (MP4 recommended)', null=True, upload_to='campus_videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Poster image shown before the video plays', null=True, upload_to='campus_videos/thumbnails/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus Video',
                'verbose_name_plural': 'Campus Videos',
                'ordering': ['display_order'],
            },
        ),
    ]
