# Generated by Django 5.2.12 on 2026-07-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_add_campus_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='Full external URL')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility Link',
                'verbose_name_plural': 'Utility Links',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Internal route (e.g. /about) or external URL (https://...)', max_length=500)),
                ('is_external', models.BooleanField(default=False, help_text='Open in new tab')),
                ('location', models.CharField(choices=[('navbar', 'Main Navbar'), ('utility', 'Utility Bar'), ('mobile_quick', 'Mobile Quick Links')], default='navbar', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name (e.g. GraduationCap)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description for featured box in mega menu')),
                ('column', models.PositiveIntegerField(default=1, help_text='Column number in dropdown (1 or 2)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item (null for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
