# Generated by Django 5.2.12 on 2026-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_seed_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label to identify this asset', max_length=200)),
                ('image', models.ImageField(help_text='Upload an image from your computer', upload_to='media-library/')),
                ('alt_text', models.CharField(blank=True, help_text='Accessible description of the image', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
