# Generated by Django 5.2.12 on 2026-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_seed_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('announcement', 'Announcement'), ('document', 'Document'), ('job', 'Job'), ('publication', 'Publication')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('original_date', models.DateField(help_text='Original publication/event date')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('original_url', models.CharField(blank=True, help_text='Link to original content', max_length=500)),
                ('file_url', models.URLField(blank=True, help_text='Link to archived file')),
                ('file_size', models.CharField(blank=True, help_text="e.g. '5.2 MB'", max_length=20)),
                ('archived_by', models.CharField(default='Admin', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archived Content',
                'verbose_name_plural': 'Archived Content',
                'ordering': ['-original_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CentrePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('career', 'Career Centre'), ('cpd', 'CPD Centre'), ('foundation-studies', 'Centre for Foundation Studies'), ('innovation', 'Innovation & Technology Centre'), ('foreign-languages', 'Institute of Foreign Languages'), ('research-institutes', 'Research Institutes')], unique=True)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=500)),
                ('about_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_location', models.CharField(blank=True, max_length=300)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Page-specific structured data')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre Page',
                'verbose_name_plural': 'Centre Pages',
            },
        ),
        migrations.CreateModel(
            name='InstitutePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('focus', models.CharField(help_text='Comma-separated focus areas', max_length=500)),
                ('director', models.CharField(max_length=200)),
                ('projects_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Institute',
                'verbose_name_plural': 'Research Institutes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.CharField(help_text='Route or external URL', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='#1E1E1E', help_text='Hex color code', max_length=20)),
                ('audience', models.CharField(help_text="e.g. 'Prospective Students'", max_length=200)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Definition',
                'verbose_name_plural': 'Portal Definitions',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(help_text="Page identifier, e.g. 'home', 'apply', 'centres/career', 'impact'", max_length=100)),
                ('section_key', models.CharField(help_text="Unique section identifier within the page, e.g. 'stats', 'steps', 'contact_info'", max_length=100)),
                ('content_type', models.CharField(choices=[('stats', 'Statistics'), ('steps', 'Process Steps'), ('cards', 'Link Cards'), ('list', 'String List'), ('contact', 'Contact Information'), ('kv', 'Key-Value Pairs'), ('hero', 'Hero Content'), ('custom', 'Custom Structured Data')], default='custom', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional section title/heading', max_length=300)),
                ('subtitle', models.CharField(blank=True, help_text='Optional section subtitle/description', max_length=500)),
                ('data', models.JSONField(blank=True, default=list, help_text='Section content as JSON array. Structure depends on content_type.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['page_key', 'display_order', 'section_key'],
                'unique_together': {('page_key', 'section_key')},
            },
        ),
    ]
