# Generated by Django 5.2.12 on 2026-08-07 17:13

from django.db import migrations, models


def seed_contact_info(apps, schema_editor):
    ContactInfo = apps.get_model('content', 'ContactInfo')
    if not ContactInfo.objects.exists():
        ContactInfo.objects.create(
            address='PMB 130, Yenagoa, Bayelsa State, Nigeria',
            phone='+234 (0) 123 456 7890',
            email='info@bmu.edu.ng',
            emergency_label='Emergency',
            emergency_phone='+234 (0) 999 888 7777',
            office_hours='Monday - Friday: 8:00 AM - 5:00 PM WAT',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Full campus address', max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Main switchboard phone number', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('emergency_label', models.CharField(blank=True, default='Emergency', help_text='Label for the emergency contact (e.g. Security)', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency / after-hours phone number', max_length=100)),
                ('office_hours', models.CharField(blank=True, help_text='Office hours, e.g. Mon-Fri 8AM - 5PM', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.RunPython(seed_contact_info, migrations.RunPython.noop),
    ]
