# Generated by Django 6.0.4 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_seed_webmaster_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission_content',
            field=models.TextField(blank=True, help_text='University mission statement'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_content',
            field=models.TextField(blank=True, help_text='University vision statement'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='why_choose',
            field=models.JSONField(blank=True, default=list, help_text='Why Choose BMU feature cards: [{icon_name, title, description}]'),
        ),
    ]
