# Generated by Django 5.2.12 on 2026-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_seed_remaining_public_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text="e.g. 'Architecture', 'Academic Life'", max_length=100)),
                ('image', models.ImageField(upload_to='campus_gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='campus_gallery/thumbnails/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus Gallery Image',
                'verbose_name_plural': 'Campus Gallery Images',
                'ordering': ['display_order'],
            },
        ),
    ]
