# Generated by Django 5.2.12 on 2026-08-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_campusgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('digital_health', 'Digital Health'), ('medical_devices', 'Medical Devices'), ('biotech', 'Biotech & Genomics'), ('ai_ml', 'AI & Machine Learning'), ('telemedicine', 'Telemedicine'), ('health_entrepreneurship', 'Health Entrepreneurship')], max_length=40)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('proposed', 'Proposed')], default='ongoing', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year the program started', null=True)),
                ('lead_unit', models.CharField(blank=True, help_text='e.g. Innovation & Technology Centre', max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='innovation/covers/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='innovation/thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL for a program video')),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('partners', models.JSONField(blank=True, default=list)),
                ('stat_1_label', models.CharField(blank=True, max_length=100)),
                ('stat_1_value', models.CharField(blank=True, max_length=50)),
                ('stat_2_label', models.CharField(blank=True, max_length=100)),
                ('stat_2_value', models.CharField(blank=True, max_length=50)),
                ('stat_3_label', models.CharField(blank=True, max_length=100)),
                ('stat_3_value', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Innovation Program',
                'verbose_name_plural': 'Innovation Programs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('research', 'Research'), ('community', 'Community & Outreach'), ('technology', 'Technology & Digital'), ('academic', 'Academic & Student')], max_length=30)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('proposed', 'Proposed')], default='ongoing', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year the project started', null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('lead_unit', models.CharField(blank=True, help_text='Unit/office leading the project', max_length=200)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget in NGN', max_digits=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL for a project video')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University Project',
                'verbose_name_plural': 'University Projects',
                'ordering': ['-year', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='InnovationProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='innovation/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.innovationprogram')),
            ],
            options={
                'verbose_name': 'Innovation Program Image',
                'verbose_name_plural': 'Innovation Program Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.universityproject')),
            ],
            options={
                'verbose_name': 'University Project Image',
                'verbose_name_plural': 'University Project Images',
                'ordering': ['order'],
            },
        ),
    ]
