# Generated by Django 5.2.12 on 2026-06-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_assigned',
            field=models.ForeignKey(blank=True, help_text='Agent currently handling this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When agent took over', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_last_response_at',
            field=models.DateTimeField(blank=True, help_text='Last agent response time', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('agent_handling', 'Agent Handling'), ('ended', 'Ended'), ('bot_only', 'Bot Only')], default='active', max_length=20),
        ),
    ]
