# Generated by Django 5.2.12 on 2026-07-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_agent_assigned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAutoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keywords', models.CharField(help_text='Comma-separated keywords/phrases that trigger this response', max_length=255)),
                ('question_pattern', models.CharField(blank=True, default='', help_text='Optional regex pattern for advanced matching', max_length=255)),
                ('response_text', models.TextField(help_text='The bot response to send')),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('admissions', 'Admissions'), ('programs', 'Programs'), ('fees', 'Fees & Payments'), ('campus', 'Campus Life'), ('research', 'Research'), ('careers', 'Careers & Jobs'), ('contact', 'Contact Info'), ('general', 'General'), ('other', 'Other')], default='general', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority responses are checked first')),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this response has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auto_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-use_count'],
            },
        ),
    ]
