# Generated by Django 5.2.12 on 2026-06-10 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionrequirement_importantdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='application',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='application',
            name='year_of_graduation',
        ),
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.ImageField(blank=True, help_text='Passport photo for profile and provisional success letter', null=True, upload_to='applications/passports/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ssce', 'SSCE/WAEC/NECO'), ('bsc', "Bachelor's Degree"), ('msc', "Master's Degree"), ('diploma', 'Diploma'), ('other', 'Other')], max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('year_of_completion', models.PositiveIntegerField()),
                ('subjects', models.JSONField(blank=True, help_text='List of subjects with grades (for SSCE/WAEC/NECO)', null=True)),
                ('grade', models.CharField(blank=True, choices=[('first', 'First Class'), ('second_upper', 'Second Class Upper'), ('second_lower', 'Second Class Lower'), ('third', 'Third Class'), ('pass', 'Pass'), ('w', 'Withdrawn')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='admissions.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['-year_of_completion'],
            },
        ),
    ]
