# Generated by Django 6.0.4 on 2026-10-08 19:44

import uuid
from django.db import migrations, models


def backfill_public_ids(apps, schema_editor):
    """Assign a unique public_id to every pre-existing application."""
    Application = apps.get_model('admissions', 'Application')
    for app in Application.objects.filter(public_id__isnull=True).iterator():
        app.public_id = uuid.uuid4()
        app.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_add_revision_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(backfill_public_ids, migrations.RunPython.noop),
    ]
