# Generated by Django 6.0.4 on 2026-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_application_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_indigene',
            field=models.BooleanField(default=False, help_text="True when a Nigerian applicant's state of origin is Bayelsa State"),
        ),
        migrations.AddField(
            model_name='application',
            name='lga',
            field=models.CharField(blank=True, default='', help_text='Local Government Area, or county/region for international applicants', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='Country of citizenship', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='state_of_origin',
            field=models.CharField(blank=True, default='', help_text='State of origin (Nigeria) or state/province (international)', max_length=100),
        ),
    ]
