# Generated by Django 5.2.12 on 2026-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgrant',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Research area category', max_length=100),
        ),
        migrations.AddField(
            model_name='researchgrant',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application deadline (for open calls)', null=True),
        ),
        migrations.AddField(
            model_name='researchgrant',
            name='eligibility',
            field=models.JSONField(blank=True, default=list, help_text='List of eligibility criteria'),
        ),
    ]
