# Generated by Django 6.0 on 2026-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_grantapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Subject area category (e.g. Malaria Research, Public Health)', max_length=100),
        ),
    ]
